### 1. 리스트조회api (아직은 파라미터가 없습니당)
GET http://localhost:8081/work
Content-Type: application/json

### 2. 등록 api
POST http://localhost:8081/work
Content-Type: application/json

{
  "work" : "api test",
  "createdBy" : "user01"
}

### 4. UPDATE API (work)
PATCH http://localhost:8081/work
Content-Type: application/json

{
  "idx" : 2,
  "work": "api update test",
  "done": "Y"
}

### 4. UPDATE API (done)
PATCH http://localhost:8081/workdone
Content-Type: application/json

{
  "idx" : 2
}


### 5. 삭제api
DELETE http://localhost:8081/work/1